export type SeoProps = Record<string, any>;
export type CalloutProps = Record<string, any>;
export type ButtonProps = Record<string, any>;
export type TagProps = Record<string, any>;
export type SocialProps = Record<string, any>;
export type Navbar = Record<string, any>;
export type MembershipCardProps = Record<string, any>;
export type GalleryImage = Record<string, any>;
export type ImageGalleryProps = Record<string, any>;
export type MediaEmbedProps = Record<string, any>;
export type HeroProps = Record<string, any>;
export type Footer = Record<string, any>;
export type ToggleCard = Record<string, any>;
export type GlobalSettingsProps = Record<string, any>;
export type AuthorProps = Record<string, any>;
export type PaginationProps = Record<string, any>;
export type ToggleCardsProps = Record<string, any>;
export type PostProps = {
  post?: any;
  previous_post?: any;
  next_post?: any;
  minutes_read?: string;
};
